services:
  - type: web
    name: oasis-travel
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_VERSION
        value: 18
