services:
  - type: web
    name: oasis-travel
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
