services:
  - type: web
    name: oasis-travel
    env: node
    buildCommand: cd backend && npm install
    startCommand: node server.js
    workingDir: backend
    envVars:
      - key: NODE_VERSION
        value: 18
